"""table Article add column sequence

Revision ID: 11a1903bc957
Revises: 628e8f922b0f
Create Date: 2024-01-19 10:50:23.057126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11a1903bc957'
down_revision = '628e8f922b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence', sa.Integer(), autoincrement=True, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('sequence')

    # ### end Alembic commands ###
