"""create database

Revision ID: 628e8f922b0f
Revises: 
Create Date: 2023-12-28 11:21:31.351142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628e8f922b0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('create_time', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('article',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('album', sa.String(length=64), nullable=True),
    sa.Column('album_order', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('keywords', sa.String(length=128), nullable=True),
    sa.Column('reading_quantities', sa.Integer(), nullable=True),
    sa.Column('comment_quantities', sa.Integer(), nullable=True),
    sa.Column('is_show', sa.Boolean(), nullable=True),
    sa.Column('is_top', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_title'), ['title'], unique=True)

    op.create_table('category',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('link', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    op.drop_table('category')
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_title'))

    op.drop_table('article')
    op.drop_table('album')
    # ### end Alembic commands ###
